mybatis:
  type-aliases-package: com.sap.domain

#mysql datasource set
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainsystem
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
    #spring.thymeleaf.encoding=UTF-8
    #spring.thymeleaf.content-type=text/html # ;charset=<encoding> is added
