mybatis:
  type-aliases-package: com.sap.domain

#mysql datasource set
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainsystem
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always




